# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  def updateVersion(options)
    if options[:version]
      version = options[:version]
    else
      version = prompt(text: "버전을 입력해주세요 (ex 1.0.0) : ")
    end

    re = /\d+.\d+.\d+/
    versionNum = version[re, 0]

    if (versionNum)
      increment_version_number(
        version_number: versionNum
      )
    elsif (version == 'major' || version == 'minor' || version == 'patch')
      increment_version_number(
        bump_type: version
      )
    elsif (version == 'maintain')
    else
      UI.user_error!("[ERROR] Wrong version!!!!!!")
    end
  end

  desc 'version update'
  lane :version do |options|
    updateVersion(options)
    increment_build_number(xcodeproj: "RecoilPuzzle.xcodeproj")
  end


  desc "firebase_app_distribution"
  lane :beta do

    setup_ci

    match(
      app_identifier: 'org.reactjs.native.example.RecoilPuzzle',
      readonly: true
    )

    build_app(workspace: "RecoilPuzzle.xcworkspace", scheme: "SkyTab_Staging", export_method:'app-store')

    firebase_app_distribution(
        testers: "ehdrnr9346@naver.com",
        release_notes: "beta test",
    )
  end

  desc "release production"
  lane :release do
    match(
      app_identifier: 'org.reactjs.native.example.RecoilPuzzle',
      readonly: true
    )

    build_app(workspace: "RecoilPuzzle.xcworkspace", scheme: "RecoilPuzzle", export_method:"app-store")

    upload_to_app_store(
      force: true,
      reject_if_possible: true,
      skip_metadata: false,
      skip_screenshots: true,
      languages: ['ko'],
      release_notes: {'ko'=>"안정성 개선"},
      submit_for_review: true,
      automatic_release: true,
    )

  end



end





