name: Publish iOS and Android App to firebase app distribution
on:
  push:
    branches: [master]

jobs:
  release-ios:
    name: Build and release iOS app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: gem install
        run: gem install bundler -v 1.17.2
      - name: Install Fastlane
        run: cd ios && bundle install && cd ..
      - name: Install packages
        run: yarn install
      - name: Install pods
        run: cd ios && pod install && cd ..
      - name: Execute Fastlane command
        run: cd ios && fastlane beta
  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: gem install
        run: gem install bundler -v 1.17.2
      - name: Install Fastlane
        run: cd android && bundle install && cd ..
      - name: Install packages
        run: yarn install
      - name: Execute Fastlane command
        run: cd android && fastlane beta
